### ISSUE TITLE
[Dependency] Proposed change to split `device_operation` into smaller binaries

### ISSUE THREAD

**Issue by junliume** [ROCmSoftwarePlatform/hipTensor#153]
**[Main Issue]**
https://github.com/ROCmSoftwarePlatform/hipTensor/blob/0b59b70357158b72032b83cb7644effb87505f70/library/src/CMakeLists.txt#L27
The line above depends on a specific component of Composable Kernel `device_operation`. However, as the binary is growing larger than 4GB, CK is planning to split the library binary up into smaller ones, e.g. :

```
build git:(lwpck-1026) ls lib/
libdevice_contraction_operations.a  libdevice_conv_operations.a  libdevice_gemm_operations.a  libdevice_other_operations.a  libdevice_reduction_operations.a  libutility.a
```
Could `hipTesor` accommodate this change in a sustainable way? i.e. not linking to a specific named library?

**Comment by cgmillette** [comment]
Hi @junliume hipTensor doesn't link to any of dynamic libs generated by CK. We provide our own instances and treat CK as a header library so we can build them. All we need from the package is headers and the include dirs so maybe if we have a consistent way to get those without linking it would be great!
